/*  r_shaders.h -- the compiled shaders, embedded.
 *
 *  r_shaders.c is generated by tools/gen_shaders.py from the GLSL in
 *  shaders/: SPIR-V for Vulkan and MSL for Metal, both checked in so a
 *  plain build needs no shader tools.  The entry point is "main" in the
 *  SPIR-V and "main0" in the MSL, which is what spirv-cross names it.
 */
#ifndef R_SHADERS_H
#define R_SHADERS_H

#include <stddef.h>
#include <stdint.h>

typedef struct
{
    const char    *name;    /* "sprite.vert"                          */
    int            stage;   /* 0 vertex, 1 fragment                   */
    const uint8_t *spv;
    size_t         spv_len;
    const uint8_t *msl;     /* NUL-terminated source text             */
    size_t         msl_len; /* without the NUL                        */
    int            num_samplers;
    int            num_uniform_buffers;
} RShaderSrc;

extern const RShaderSrc r_shaders[];
extern const int        r_n_shaders;

const RShaderSrc *r_shader_find(const char *name);

#endif /* R_SHADERS_H */
