/*  r_tables.c -- GENERATED by tools/gen_render_tables.py, do not edit.
 *
 *  Source: the A5 initialised-data image reconstructed from DATA 0, so
 *  every value traces back to an offset in the shipped binary.
 */
#include "r_tables.h"

/*  XTER -> terrain shape id, the word table at A5-0x493E that the tile
 *  drawing routine at $167CC indexes with 2*XTER.  Zero means the value
 *  has no art and nothing is drawn.
 *
 *    0x00..0x0E  dry land, fourteen slope shapes
 *    0x10..0x1F  fully submerged -- every one of them is open water
 *    0x20..0x2E  shore shapes, and 0x30..0x3E the same art again at a
 *                different water level
 *    0x40..0x45  land on two opposite edges: a one-tile channel
 *    0x46..0x4D  the second slope set
 */
const uint16_t R_XTER_TILE[256] = {
     256,  257,  258,  259,  260,  261,  262,  263,  /* 0x00 */
     264,  265,  266,  267,  268,  269,  269,    0,  /* 0x08 */
     270,  270,  270,  270,  270,  270,  270,  270,  /* 0x10 */
     270,  270,  270,  270,  270,  270,  270,  270,  /* 0x18 */
     270,  271,  272,  273,  274,  275,  276,  277,  /* 0x20 */
     278,  279,  280,  281,  282,  283,  284,    0,  /* 0x28 */
     270,  271,  272,  273,  274,  275,  276,  277,  /* 0x30 */
     278,  279,  280,  281,  282,  283,  284,    0,  /* 0x38 */
     285,  286,  287,  288,  289,  290,  305,  306,  /* 0x40 */
     307,  308,  309,  310,  311,  312,  313,  314,  /* 0x48 */
     315,  316,  317,  318,  318,    0,  305,  306,  /* 0x50 */
     307,  308,  309,  310,  311,  312,  313,  314,  /* 0x58 */
     315,  316,  317,  318,  318,    0,  305,  306,  /* 0x60 */
     307,  308,  309,  310,  311,  312,  313,  314,  /* 0x68 */
     315,  316,  317,  318,  318,    0,  305,  305,  /* 0x70 */
     305,  305,  305,  305,  305,  305,  305,  305,  /* 0x78 */
     305,  305,  305,  305,  305,  305,  305,  305,  /* 0x80 */
     305,  305,  305,  305,  258,  772, 1286, 1800,  /* 0x88 */
    2314,  513,  513,  512,    0,    0,    0,    0,  /* 0x90 */
       0,    0,    0,    0,    0,  513,    0,  258,  /* 0x98 */
     258,    0, 2828, 2828, 2828, 2828, 3341, 3341,  /* 0xA0 */
    3341, 3341,    0,    0, 3856, 4370, 4884, 5398,  /* 0xA8 */
    5912, 6426, 6912,    0,   28, 7454, 7968, 8482,  /* 0xB0 */
    8996, 9510, 10024, 10511, 4113, 4650, 11052, 11566,  /* 0xB8 */
    12080, 12594,  768,    1,  258,  516, 1028, 1028,  /* 0xC0 */
    1028, 1028, 17219, 7967, 1799, 57600, 57600, 57600,  /* 0xC8 */
       8,   16,   32, 7765, 28257, 25196, 25888, 29807,  /* 0xD0 */
    8289, 27756, 28515, 24948, 25888, 10100, 26725, 21352,  /* 0xD8 */
    24944, 25971, 9996, 21089, 26995, 25956, 8279, 26994,  /* 0xE0 */
    25971, 2898, 24937, 27680, 17010, 26980, 26469,    8,  /* 0xE8 */
    17249, 30067, 25975, 24953, 3666, 24937, 29545, 28263,  /* 0xF0 */
    8258, 29289, 25703, 25866, 21365, 29552, 25966, 29545,  /* 0xF8 */
};

/*  Thing type -> base shape id (A5-0x63CE).  Type 0 is an empty slot;
 *  types 12 and 13 have a base but their dispatch arm at $A128 is a
 *  bare branch to the exit, so they are never drawn. */
const uint16_t R_THING_SHAPE[17] = {
    0, 359, 364, 369, 390, 490, 387, 382, 383, 380, 374, 374, 374, 374, 384, 497, 495};

/*  Minimum zoom level (0=8px, 1=16px, 2=32px) at which each type is
 *  drawn at all, from A5-0x63AC.  $A05E compares g_zoom against this
 *  and skips when lower.  Type 13's threshold of 3 exceeds the
 *  highest zoom, so it never draws. */
const uint16_t R_THING_MINZOOM[17] = {
    0, 0, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 3, 0, 0, 2};

/*  Heading 0..7 -> which of the five sprites, and whether to mirror
 *  it (A5-0x6348 and A5-0x6340).  Eight directions from five images. */
const uint8_t R_DIR_FRAME[8] = {1, 2, 3, 4, 3, 2, 1, 0};
const uint8_t R_DIR_FLIP[8]  = {0, 0, 0, 0, 1, 1, 1, 0};

/*  Road vehicles, thing types 10 and 11 ($A7E0).  The sprite is chosen
 *  by the road tile under the vehicle, not by its heading:
 *    d4 = XBLD - 0x2C, rejected outside 0..0x22, then -6 above 0x12
 *    and a further -4 above 0x16;  slot = R_VEH_SLOT[d4];  a slot of
 *    50 means resolve it from thing[+8] through R_VEH_SLOT8 instead.
 *  The slot then picks the shape offset, the blitter's mirror flag and
 *  two sub-tile nudges. */
const uint8_t R_VEH_SLOT[28] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 50, 50, 50, 50, 50, 10, 11, 12, 13, 1, 0, 0, 1, 1, 0, 0, 0, 0};
const uint8_t R_VEH_SLOT8[8] = {0, 17, 1, 16, 0, 17, 1, 16};
const uint8_t R_VEH_SHAPE[20] = {0, 0, 3, 3, 4, 4, 2, 1, 2, 1, 3, 3, 4, 4, 0, 0, 2, 1, 9, 9};
const uint8_t R_VEH_FLIP[20]  = {0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 9, 9};
const uint8_t R_VEH_DX[20]    = {0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0};
const int16_t R_VEH_DY[20]    = {0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 8, 8, 6, 6, 0, 0, 0, 6, 0, 0};

/*  Traffic ($17612).  A road tile draws a car when the XTRF density at
 *  (row/2, col/2) exceeds a threshold -- 0x1C for the highway shapes
 *  73..80, 0x55 otherwise -- and a heavier variant above 0x38 / 0xAA.
 *  The sprite is 399 + index. */
/*  A zone building in the underground view is not drawn as itself:
 *  $16512 draws shape 354 + R_UGND_ZONE[XZON & 0x0F]. */
const uint8_t R_UGND_ZONE[16] = {
    3, 0, 0, 1, 1, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4};

/*  A thing is not pinned to its tile: $A2F6 and $A322 project a
 *  sub-tile position (XTHG +6, +7) with these divisors, one per
 *  zoom.  Index 3 is unused and zero -- never divide by it. */
const uint8_t R_THING_DIVX[4] = {
    4, 2, 1, 0};

const uint8_t R_THING_DIVY[4] = {
    8, 4, 2, 0};

/*  SC2K does not rotate its animated palette runs -- it keeps two
 *  colour tables, swaps them every 12 ticks, and rebuilds one from
 *  the other through these permutations ($9770, $97FA):
 *      new[i] = prev[perm[i]]
 *  A is 3 eight-cycles, a four-cycle, a fixed point, then an
 *  eight-cycle, a four-cycle and an eight-cycle running the OTHER
 *  way; B is seven swaps and a fixed point -- a blink, not a flow.
 *  Rotating all 49 as one block mixes unrelated ramps together. */
/*  Thing types 0, 4 and 9 do NOT use the eight-heading tables the
 *  other arms use: $A214 reads a four-entry pair instead ($A224 for
 *  the mirror).  Using the eight-entry ones picks the wrong frame. */
const uint8_t R_DIR_FRAME4[4] = {
    0, 1, 1, 0};

const uint8_t R_DIR_FLIP4[4] = {
    0, 0, 1, 1};

const uint8_t R_ANIM_PERM_A[49] = {
    1, 2, 3, 4, 5, 6, 7, 0, 9, 10, 11, 12, 13, 14, 15, 8, 17, 18, 19, 20, 21, 22, 23, 16, 25, 26, 27, 24, 28, 36, 29, 30, 31, 32, 33, 34, 35, 40, 37, 38, 39, 48, 41, 42, 43, 44, 45, 46, 47};

const uint8_t R_ANIM_PERM_B[15] = {
    1, 0, 3, 2, 5, 4, 7, 6, 9, 8, 11, 10, 13, 12, 14};

const uint8_t R_TRAFFIC_CAR[80] = {
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 1, 2, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 1, 2, 1, 2, 0, 0, 11, 12, 11, 12, 11, 12, 11, 12, 13, 13, 13, 13, 13, 13, 13, 13, 0, 0, 0, 0, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 0, 0, 0};
/*  The underground view lays its own ground: a wireframe lattice
 *  following the terrain, shapes 305..318, from A5-0x48B2 ($1627E).
 *  Not the surface terrain -- that is a different table. */
const uint16_t R_UGND_GROUND[128] = {
     305,  306,  307,  308,  309,  310,  311,  312,
     313,  314,  315,  316,  317,  318,  318,    0,
     305,  306,  307,  308,  309,  310,  311,  312,
     313,  314,  315,  316,  317,  318,  318,    0,
     305,  306,  307,  308,  309,  310,  311,  312,
     313,  314,  315,  316,  317,  318,  318,    0,
     305,  305,  305,  305,  305,  305,  305,  305,
     305,  305,  305,  305,  305,  305,  305,  305,
     305,  305,  305,  305,  305,  305,  258,  772,
    1286, 1800, 2314,  513,  513,  512,    0,    0,
       0,    0,    0,    0,    0,    0,    0,  513,
       0,  258,  258,    0, 2828, 2828, 2828, 2828,
    3341, 3341, 3341, 3341,    0,    0, 3856, 4370,
    4884, 5398, 5912, 6426, 6912,    0,   28, 7454,
    7968, 8482, 8996, 9510, 10024, 10511, 4113, 4650,
    11052, 11566, 12080, 12594,  768,    1,  258,  516,
};

const uint8_t R_TRAFFIC_HEAVY[28] = {
    0, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 15, 16, 17, 18, 42, 43, 44, 45, 46, 47, 48, 49, 50};

