#!/usr/bin/env python3
"""Compile the renderer's GLSL into what SDL_GPU accepts, and embed it.

    python3 tools/gen_shaders.py          # -> src/render/shaders.c

Every shader in src/render/shaders/ is authored once, in GLSL 450 with
Vulkan semantics, and compiled to SPIR-V (glslang) for the Vulkan backend
and to MSL (spirv-cross) for Metal.  Both outputs are embedded in a
generated C file that is checked in, so a plain build needs neither tool.

Binding conventions, which are SDL_GPU's for SPIR-V and reproduced for MSL
by `--msl-decoration-binding`:
    vertex   : uniform buffers in set 1, bindings from 0
    fragment : sampled textures in set 2, uniform buffers in set 3
The counts SDL_CreateGPUShader wants are read off the GLSL text.

Standard library only, so it runs wherever the game builds.
"""
import pathlib, re, subprocess, sys, tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src/render/shaders"
OUT_C = ROOT / "src/render/generated/shaders.c"

SHADERS = [
    "sprite.vert", "sprite.frag", "shadow.frag",
    "resolve.vert", "resolve.frag",
    "terrain.vert", "terrain.frag",
    "sprite_water.frag",
]


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit("failed: " + " ".join(cmd))
    return r


def counts(glsl):
    samplers = len(re.findall(r"\buniform\s+u?sampler2D\b", glsl))
    ubos = len(re.findall(r"\buniform\s+\w+\s*\{", glsl))
    return samplers, ubos


def c_bytes(name, data):
    lines = ["static const uint8_t %s[%d] = {" % (name, len(data))]
    for i in range(0, len(data), 16):
        lines.append("    " + " ".join("%d," % b for b in data[i:i + 16]))
    lines.append("};")
    return "\n".join(lines)


def main():
    out = []
    w = out.append
    w("/*  shaders.c -- GENERATED by tools/gen_shaders.py, do not edit.")
    w(" *")
    w(" *  SPIR-V from glslang and MSL from spirv-cross, for each shader in")
    w(" *  src/render/shaders/.  Regenerate with:")
    w(" *      cmake --build build --target render-shaders")
    w(" */")
    w('#include "shaders.h"')
    w("")
    w("#include <string.h>")
    w("")
    table = []
    with tempfile.TemporaryDirectory() as td:
        td = pathlib.Path(td)
        for name in SHADERS:
            src = SRC / name
            if not src.exists():
                continue
            glsl = src.read_text(encoding="utf-8")
            stage = "vertex" if name.endswith(".vert") else "fragment"
            spv = td / (name + ".spv")
            msl = td / (name + ".metal")
            run(["glslang", "-V", str(src), "-o", str(spv)])
            run(["spirv-cross", "--msl", "--msl-version", "20100",
                 "--msl-decoration-binding", str(spv), "--output", str(msl)])
            ident = name.replace(".", "_")
            spv_b = spv.read_bytes()
            msl_b = msl.read_bytes() + b"\0"
            w("/* %s */" % name)
            w(c_bytes(ident + "_spv", spv_b))
            w(c_bytes(ident + "_msl", msl_b))
            w("")
            ns, nu = counts(glsl)
            table.append((name, stage, ident, len(spv_b), len(msl_b) - 1, ns, nu))
    w("const RShaderSrc shaders_all[] = {")
    for name, stage, ident, ls, lm, ns, nu in table:
        w('    {"%s", %d, %s_spv, %d, %s_msl, %d, %d, %d},'
          % (name, 0 if stage == "vertex" else 1, ident, ls, ident, lm, ns, nu))
    w("};")
    w("const int n_shaders = %d;" % len(table))
    w("")
    w("const RShaderSrc *shader_find(const char *name)")
    w("{")
    w("    int i;")
    w("    for (i = 0; i < n_shaders; ++i)")
    w("        if (strcmp(shaders_all[i].name, name) == 0)")
    w("            return &shaders_all[i];")
    w("    return NULL;")
    w("}")
    open(OUT_C, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    print("wrote %s: %d shaders" % (OUT_C.relative_to(ROOT), len(table)))
    for name, stage, ident, ls, lm, ns, nu in table:
        print("  %-14s %-8s spv %5d B  msl %5d B  samplers %d  uniforms %d"
              % (name, stage, ls, lm, ns, nu))


if __name__ == "__main__":
    main()
