#!/usr/bin/env python3
"""Generate src/render/tables.c from the binary's own global image.

Nothing here is hand-typed.  The terrain table is the word table the tile
drawing routine at $167CC indexes with XTER:

    016872: lea.l -$493e(a5), a0
    016876: adda.w d5, a0
    016878: move.w (a0, d5.w), d5      ; A5-0x493E + 2*XTER

Run it from the repository root:  python3 tools/gen_render_tables.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from thinkdata import build, bytesat

XTER_TABLE   = -0x493E
THING_SHAPE  = -0x63CE   # word per thing type: base shape
THING_ZOOM   = -0x63AC   # word per thing type: minimum zoom to draw at
DIR_FRAME    = -0x6348   # byte per heading 0..7: which of five sprites
DIR_FLIP     = -0x6340   # byte per heading 0..7: draw it mirrored
#  Road vehicles (thing types 10 and 11), from $A7E0.  The sprite follows the
#  ROAD's shape, not the vehicle's heading.
VEH_SLOT     = -0x62E6   # byte: (XBLD - 0x2C, adjusted) -> slot; 50 = defer
VEH_SLOT8    = -0x62CA   # byte: thing[+8] -> slot, when the above is 50
VEH_SHAPE    = -0x62C2   # byte: slot -> shape offset 0..4
VEH_FLIP     = -0x62AE   # byte: slot -> the blitter's variant flag
VEH_DX       = -0x629A   # byte: slot -> extra x nudge
VEH_DY       = -0x6286   # word: slot -> extra y nudge
#  Traffic, from $17612.  Cars are drawn from the XTRF density layer, not
#  from XTHG; the road's own shape picks which car sprite.
TRAF_CAR     = -0x4826   # byte: XBLD-29 -> car sprite index, 0 = none
TRAF_HEAVY   = -0x47D6   # byte: car index -> its heavy-traffic variant
UGND_GROUND  = -0x48B2   # word: XTER -> the underground view's ground shape
UGND_ZONE    = -0x47BA   # byte: XZON zone type -> offset from shape 354
THING_DIVX   = -0x6330   # byte: zoom -> divisor for a thing's sub-tile x
THING_DIVY   = -0x632C   # byte: zoom -> divisor for a thing's sub-tile y
DIR_FRAME4   = -0x6338   # byte[4]: heading -> frame, for thing types 0/4/9
DIR_FLIP4    = -0x6334   # byte[4]: heading -> mirror, for the same
ANIM_PERM_A  = -0x64B0   # word[49]: the palette permutation for run 155..203
ANIM_PERM_B  = -0x644E   # word[15]: the palette permutation for run 224..238
OUT = Path(__file__).resolve().parent.parent / "src" / "render" / "tables.c"


def main():
    img = build()
    def words(off, n):
        r = bytesat(img, off, n * 2)
        return [(r[i] << 8) | r[i + 1] for i in range(0, len(r), 2)]

    tbl = words(XTER_TABLE, 256)

    lines = []
    a = lines.append
    a("/*  tables.c -- GENERATED by tools/gen_render_tables.py, do not edit.")
    a(" *")
    a(" *  Source: the A5 initialised-data image reconstructed from DATA 0, so")
    a(" *  every value traces back to an offset in the shipped binary.")
    a(" */")
    a('#include "tables.h"')
    a("")
    a("/*  XTER -> terrain shape id, the word table at A5-0x493E that the tile")
    a(" *  drawing routine at $167CC indexes with 2*XTER.  Zero means the value")
    a(" *  has no art and nothing is drawn.")
    a(" *")
    a(" *    0x00..0x0E  dry land, fourteen slope shapes")
    a(" *    0x10..0x1F  fully submerged -- every one of them is open water")
    a(" *    0x20..0x2E  shore shapes, and 0x30..0x3E the same art again at a")
    a(" *                different water level")
    a(" *    0x40..0x45  land on two opposite edges: a one-tile channel")
    a(" *    0x46..0x4D  the second slope set")
    a(" */")
    a("const uint16_t R_XTER_TILE[256] = {")
    for base in range(0, 256, 8):
        row = ", ".join("%4d" % tbl[base + k] for k in range(8))
        a("    %s,%s" % (row, "  /* 0x%02X */" % base))
    a("};")
    a("")

    #  Things.  $A032 reads the type at +0, looks the minimum zoom up in
    #  A5-0x63AC and skips the thing entirely below it, then dispatches on
    #  type through the jump table at $A0BE.  Most arms compute
    #  base[type] + frame[heading], with a mirror flag for the headings
    #  that reuse a sprite.
    ts = words(THING_SHAPE, 17)
    tz = words(THING_ZOOM, 17)
    df = list(bytesat(img, DIR_FRAME, 8))
    dl = list(bytesat(img, DIR_FLIP, 8))
    a("/*  Thing type -> base shape id (A5-0x63CE).  Type 0 is an empty slot;")
    a(" *  types 12 and 13 have a base but their dispatch arm at $A128 is a")
    a(" *  bare branch to the exit, so they are never drawn. */")
    a("const uint16_t R_THING_SHAPE[17] = {")
    a("    " + ", ".join("%d" % v for v in ts) + "};")
    a("")
    a("/*  Minimum zoom level (0=8px, 1=16px, 2=32px) at which each type is")
    a(" *  drawn at all, from A5-0x63AC.  $A05E compares g_zoom against this")
    a(" *  and skips when lower.  Type 13's threshold of 3 exceeds the")
    a(" *  highest zoom, so it never draws. */")
    a("const uint16_t R_THING_MINZOOM[17] = {")
    a("    " + ", ".join("%d" % v for v in tz) + "};")
    a("")
    a("/*  Heading 0..7 -> which of the five sprites, and whether to mirror")
    a(" *  it (A5-0x6348 and A5-0x6340).  Eight directions from five images. */")
    a("const uint8_t R_DIR_FRAME[8] = {" + ", ".join(str(v) for v in df) + "};")
    a("const uint8_t R_DIR_FLIP[8]  = {" + ", ".join(str(v) for v in dl) + "};")
    a("")
    a("/*  Road vehicles, thing types 10 and 11 ($A7E0).  The sprite is chosen")
    a(" *  by the road tile under the vehicle, not by its heading:")
    a(" *    d4 = XBLD - 0x2C, rejected outside 0..0x22, then -6 above 0x12")
    a(" *    and a further -4 above 0x16;  slot = R_VEH_SLOT[d4];  a slot of")
    a(" *    50 means resolve it from thing[+8] through R_VEH_SLOT8 instead.")
    a(" *  The slot then picks the shape offset, the blitter's mirror flag and")
    a(" *  two sub-tile nudges. */")
    a("const uint8_t R_VEH_SLOT[28] = {" + ", ".join(str(v) for v in bytesat(img, VEH_SLOT, 28)) + "};")
    a("const uint8_t R_VEH_SLOT8[8] = {" + ", ".join(str(v) for v in bytesat(img, VEH_SLOT8, 8)) + "};")
    a("const uint8_t R_VEH_SHAPE[20] = {" + ", ".join(str(v) for v in bytesat(img, VEH_SHAPE, 20)) + "};")
    a("const uint8_t R_VEH_FLIP[20]  = {" + ", ".join(str(v) for v in bytesat(img, VEH_FLIP, 20)) + "};")
    a("const uint8_t R_VEH_DX[20]    = {" + ", ".join(str(v) for v in bytesat(img, VEH_DX, 20)) + "};")
    a("const int16_t R_VEH_DY[20]    = {" + ", ".join(str(v) for v in words(VEH_DY, 20)) + "};")
    a("")
    a("/*  Traffic ($17612).  A road tile draws a car when the XTRF density at")
    a(" *  (row/2, col/2) exceeds a threshold -- 0x1C for the highway shapes")
    a(" *  73..80, 0x55 otherwise -- and a heavier variant above 0x38 / 0xAA.")
    a(" *  The sprite is 399 + index. */")
    a("/*  A zone building in the underground view is not drawn as itself:")
    a(" *  $16512 draws shape 354 + R_UGND_ZONE[XZON & 0x0F]. */")
    a("const uint8_t R_UGND_ZONE[16] = {")
    a("    " + ", ".join(str(v) for v in bytesat(img, UGND_ZONE, 16)) + "};")
    a("")
    a("/*  A thing is not pinned to its tile: $A2F6 and $A322 project a")
    a(" *  sub-tile position (XTHG +6, +7) with these divisors, one per")
    a(" *  zoom.  Index 3 is unused and zero -- never divide by it. */")
    a("const uint8_t R_THING_DIVX[4] = {")
    a("    " + ", ".join(str(v) for v in bytesat(img, THING_DIVX, 4)) + "};")
    a("")
    a("const uint8_t R_THING_DIVY[4] = {")
    a("    " + ", ".join(str(v) for v in bytesat(img, THING_DIVY, 4)) + "};")
    a("")
    a("/*  SC2K does not rotate its animated palette runs -- it keeps two")
    a(" *  colour tables, swaps them every 12 ticks, and rebuilds one from")
    a(" *  the other through these permutations ($9770, $97FA):")
    a(" *      new[i] = prev[perm[i]]")
    a(" *  A is 3 eight-cycles, a four-cycle, a fixed point, then an")
    a(" *  eight-cycle, a four-cycle and an eight-cycle running the OTHER")
    a(" *  way; B is seven swaps and a fixed point -- a blink, not a flow.")
    a(" *  Rotating all 49 as one block mixes unrelated ramps together. */")
    a("/*  Thing types 0, 4 and 9 do NOT use the eight-heading tables the")
    a(" *  other arms use: $A214 reads a four-entry pair instead ($A224 for")
    a(" *  the mirror).  Using the eight-entry ones picks the wrong frame. */")
    a("const uint8_t R_DIR_FRAME4[4] = {")
    a("    " + ", ".join(str(v) for v in bytesat(img, DIR_FRAME4, 4)) + "};")
    a("")
    a("const uint8_t R_DIR_FLIP4[4] = {")
    a("    " + ", ".join(str(v) for v in bytesat(img, DIR_FLIP4, 4)) + "};")
    a("")
    a("const uint8_t R_ANIM_PERM_A[49] = {")
    a("    " + ", ".join(str(v) for v in words(ANIM_PERM_A, 49)) + "};")
    a("")
    a("const uint8_t R_ANIM_PERM_B[15] = {")
    a("    " + ", ".join(str(v) for v in words(ANIM_PERM_B, 15)) + "};")
    a("")
    a("const uint8_t R_TRAFFIC_CAR[80] = {")
    a("    " + ", ".join(str(v) for v in bytesat(img, TRAF_CAR, 80)) + "};")
    a("/*  The underground view lays its own ground: a wireframe lattice")
    a(" *  following the terrain, shapes 305..318, from A5-0x48B2 ($1627E).")
    a(" *  Not the surface terrain -- that is a different table. */")
    a("const uint16_t R_UGND_GROUND[128] = {")
    for base in range(0, 128, 8):
        a("    " + ", ".join("%4d" % v for v in words(UGND_GROUND, 128)[base:base + 8]) + ",")
    a("};")
    a("")
    a("const uint8_t R_TRAFFIC_HEAVY[28] = {")
    a("    " + ", ".join(str(v) for v in bytesat(img, TRAF_HEAVY, 28)) + "};")
    a("")
    #  Explicit encoding and newline: Path.write_text has no newline= before
    #  Python 3.10, and a CRLF here would make the generated file differ
    #  between platforms.
    with open(str(OUT), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    used = sorted({v for v in tbl if v})
    print("wrote %s" % OUT)
    print("  %d non-zero entries, tile ids %d..%d" %
          (sum(1 for v in tbl if v), used[0], used[-1]))


if __name__ == "__main__":
    main()
