"""Generate src/sim/generated/tables.c from the binary's own initialized-global image.

Nothing here is hand-typed: every value is read out of the A5 image that
thinkdata.py rebuilds from the compressed DATA 0 resource, so each table
traces back to an offset in the shipped binary.  The one exception is
PLANT_OUTPUT, which lives in code rather than data -- see the comment.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from thinkdata import build, rd, words, bytesat

NAME_BASE = -0x6D42          # buildingNames[id] = A5 + NAME_BASE + 16*id
img = build()

#  The name table only really starts at 0xC6.  Below that the fixed 16-byte
#  stride runs off the end of it and into the surrounding string pool, which
#  is where entries like "erver Volume Dis" came from -- fragments of Mac OS
#  error strings, not building names.  Nothing below 0xC6 is emitted.
FIRST_NAMED = 0xC6

def cstr(b):
    s = b.split(b"\0")[0].decode("mac_roman", "replace")
    s = "".join(ch for ch in s if ch.isprintable()).strip()
    return s.replace("\\", "\\\\").replace('"', '\\"')

out = []
w = out.append
w('/*  tables.c -- GENERATED by tools/gen_tables.py, do not edit.')
w(' *')
w(' *  Source: the A5 initialized-data image reconstructed from the DATA 0')
w(' *  resource of SimCity 2000(R) 1.2.  A5 offsets are given per table.')
w(' */')
w('#include "sc2k.h"')
w('')

# ---- building names (only 0xC6..0xFF are real entries) --------------
names = {}
for i in range(FIRST_NAMED, 256):
    names[i] = cstr(rd(img, NAME_BASE + 16*i, 16))

# the same names as data, for the Python side; nothing below FIRST_NAMED,
# so no string-pool fragments leak in
import json as _json
_json.dump({"0x%02X" % i: n for i, n in sorted(names.items())},
           open(os.path.join(os.path.dirname(__file__), "..", "out",
                             "bldnames.json"), "w"), indent=1)

def emit_bytes(name, a5, n, comment):
    v = bytesat(img, a5, n)
    w('/* %s */' % comment)
    w('const uint8_t %s[%d] = {' % (name, n))
    for i in range(0, n, 12):
        w('    ' + ' '.join('%3d,' % x for x in v[i:i+12]))
    w('};'); w('')

def emit_longs(name, a5, n, comment):
    import struct
    b = rd(img, a5, 4 * n)
    v = struct.unpack('>%di' % n, b)
    w('/* %s */' % comment)
    w('const int32_t %s[%d] = {' % (name, n))
    for i in range(0, n, 8):
        w('    ' + ' '.join('%6d,' % x for x in v[i:i+8]))
    w('};'); w('')


def emit_singles(name, a5, n, comment):
    import struct
    b = rd(img, a5, 4 * n)
    v = struct.unpack('>%df' % n, b)
    w('/* %s */' % comment)
    w('const float %s[%d] = {' % (name, n))
    def lit(x):
        t = '%.9g' % x            # a single round-trips at nine digits
        if '.' not in t and 'e' not in t and 'n' not in t:
            t += '.0'
        return t + 'f,'
    for i in range(0, n, 6):
        w('    ' + ' '.join(lit(x) for x in v[i:i+6]))
    w('};'); w('')


def emit_words(name, a5, n, comment):
    v = words(img, a5, n)
    w('/* %s */' % comment)
    w('const int16_t %s[%d] = {' % (name, n))
    for i in range(0, n, 10):
        w('    ' + ' '.join('%5d,' % x for x in v[i:i+10]))
    w('};'); w('')

#  ---- power plant output: this one is code, not data ----------------
#
#  Transcribed from the jump table at $21158 and the ten cases from
#  $21174 to $211D2.  It is the one column here that is NOT read out of
#  the data image, because the original encodes it as a switch rather
#  than an array.  Two entries are negative sentinels: the game computes
#  those instead of loading a constant.
#      -1  Wind   ($211DA)  output = (altitude + rand) / 2
#      -2  Solar  ($2119C)  output = rand % ((100 - weather)/10) + 5
_POWER = {0xC6: 40, 0xC7: 40, 0xC8: -1, 0xC9: 11, 0xCA: 48,
          0xCB: 111, 0xCC: -2, 0xCD: 355, 0xCE: 555, 0xCF: 44}

#  ---- BUILDING[]: everything the simulation knows about a tile id ----
#
#  Six of these columns are separate arrays in the original, and they do
#  NOT share an index base: four start at id 0x70, the names step 16 bytes
#  from 0x00, and the department masks are keyed by the raw id.  Folding
#  them into one table indexed by id is what removes that hazard.
import gen_budget as _budget
from tset import heights as _tset_heights
_dept  = _budget.masks()                                    # id 0x00..0x6F
_sprh  = _tset_heights()                                    # id 0x00..0xFF
_poll  = bytesat(img, -0x3A12, 144)                         # id - 0x70
_pop   = bytesat(img, -0x3982,  86)                         # id - 0x70
#  Both of these are 86 entries long as the game uses them for zone
#  buildings, and $31D2E indexes them by id - 0x70 for EVERY id from
#  $70 up -- so ids $C6 and above read past the end into whatever the
#  A5 image holds next.  That is not a bug to be tidied away: the
#  values are stable data and the original acts on them.  A runway
#  ($E4) standing on an industrial zone reads tier 514 this way, and
#  $31DF4 then credits GROWTH_TABLE[514].  Read the full 144 so the
#  reconstruction sees what the original sees.
_tier  = words(img,   -0x1570, 144)                         # id - 0x70
_flag  = bytesat(img, -0x14C4, 144)                         # id - 0x70
_size  = words(img,   -0x1252, 144)   # id - 0x70; `moveq #$90` at $768A
                                     # sign-extends to -112, so the index
                                     # is id-0x70 and the stride is a WORD

def _at(tbl, i, default=0):
    j = i - 0x70
    return tbl[j] if 0 <= j < len(tbl) else default

w('/*  Everything the simulation knows about one tile id.  In the original')
w(" *  these are six separate arrays that do NOT share an index base: the")
w(' *  names step 16 bytes from A5-0x6D42, four of the columns start at id')
w(' *  0x70, and the department masks are keyed by the raw id.  Indexing')
w(' *  all of it by id is the whole point of the merge.')
w(' *')
w(' *    name        A5-0x6D42, real only from 0xC6 up')
w(' *    pollution   A5-0x3A12, read by the city scan at $2317E')
w(' *    population  A5-0x3982, read by $23D10')
w(' *    tier        A5-0x1570, 1..4, zone buildings only, $31D2E')
w(' *    tier_flag   A5-0x14C4, gates growth at $31DD0')
w(' *    size        A5-0x1252, footprint edge, $7694')
w(' *    dept        computed, see tools/gen_budget.py')
w(' *    power       transcribed from the switch at $21174; -1 and -2 are')
w(' *                sentinels for the two plants whose output is computed')
w(' *    sprite_h    the shape height out of the TSET resource, which the')
w(' *                simulation reads too: $C2DA divides it by three and')
w(' *                crashes an aeroplane into anything taller */')
w('const Building BUILDING[256] = {')
for i in range(256):
    nm = '"%s"' % names[i] if i in names else 'NULL'
    w('    [0x%02X] = {%-18s %3d, %3d, %2d, %2d, %2d, 0x%04X, %4d, %3d},'
      % (i, nm + ',', _at(_poll, i), _at(_pop, i), _at(_tier, i),
         _at(_flag, i), _at(_size, i, 1), _dept[i] if i < 0x70 else 0,
         _POWER.get(i, 0), _sprh[i]))
w('};')
w('')

emit_bytes('WEATHER_CLOUD', 0xA4E, 12,
           'A5+0x0A4E  read at $34C90.  What cloud cover each of the twelve'
           ' weather states settles toward; the solar plant reads it.')
emit_bytes('WEATHER_WIND', 0xA5A, 12,
           'A5+0x0A5A  read at $34CB6.  The wind each state settles toward,'
           ' which is what the wind plant turns into output.')
emit_bytes('WEATHER_TEMP', 0xA66, 12,
           'A5+0x0A66  read at $34CDC.  The temperature each state settles'
           ' toward.')
emit_bytes('WEATHER_NEXT', 0xA72, 4 * 12 * 8,
           'A5+0x0A72  read at $34C66.  The weather walks from state to'
           ' state: eight equally likely successors per state, twelve states,'
           ' and a separate set of twelve for each of the four seasons.'
           '  Indexed [season][state][roll].')

emit_bytes('MICRO_CLASS', -0x5D42, 58,
           'A5-0x5D42.  Which XMIC slot a building gets, by id from '
           '0xC6.  Zero means it keeps no record at all; 0x11 and above '
           'is a FIXED slot, that value less sixteen -- the systems that '
           'share one record between every copy of themselves; anything '
           'else takes the first free slot from ten up ($EEC8).')

emit_bytes('MICRO_LABEL', -0x60E2, 58 * 16,
           'A5-0x60E2.  The default name a new XMIC record is given, '
           'sixteen bytes per building id from 0xC6, Pascal-counted.  '
           '$EFDA copies it in unless a fixed-slot record already has a '
           'name of its own.')

emit_words('MICRO_REBUILD_IDX', -0x5198, 11,
           'A5-0x5198.  $10392 in the microsim: a worn-out power plant\'s '
           'building id, less 0xC6, indexes this to reach BUILD_COST.  '
           'Eleven entries, $C6..$D0; past that the table runs into the '
           'string pool.')

emit_longs('BUILD_COST', 0x6A6, 24,
           'A5+0x616 + 0x90.  What the build menu charges, indexed through '
           'MICRO_REBUILD_IDX.  The nine power plants come out at the '
           'prices the game charges: hydro 400, wind 100, gas 2000, oil '
           '6600, nuclear 15000, solar 1300, microwave 28000, fusion '
           '40000, coal 4000.')

emit_words('DISASTER_ODDS', -0x15EA, 4,
           'A5-0x15EA  read twice at $310B0 and $310D0, indexed by difficulty.'
           '  Nothing happens at all until the city is this many months old,'
           ' and then it is a one-in-this chance each time phase 24 runs:'
           ' 100 on the easiest setting, 30 on the hardest.  Entry 0 unused.')

emit_words('DEMAND_TAX', -0x1404, 24,
           'A5-0x1404  read at $346CE.  Indexed by a department funding'
           ' level, this is what the tax rate contributes to that zone\'s'
           ' demand each month: +200 at no tax, falling to -700.')
emit_singles('DEMAND_LEVEL', -0x12FA, 4,
             'A5-0x12FA  read at $341D8, indexed by difficulty.  The'
             ' multiplier industrial demand is scaled by, so an easier game'
             ' asks more of industry.  Entry 0 is unused.')

emit_words('GROWTH_TABLE', -0x141E, 515,
           'A5-0x141E  indexed by building tier at $31DDA.  Only the first'
           ' 32 entries are the table proper; the tier that indexes it comes'
           ' from A5-0x1570, which is itself read past its end, so the index'
           ' reaches 514.  Everything past 32 is neighbouring A5 data that'
           ' the original reads and acts on, so it is carried here too.')
emit_words('ROT_CORNER_MASK', -0x7DD4, 4,
           'A5-0x7DD4  XZON corner bit selected by map rotation. $3173A')
emit_words('DEPT_YEAR_DIVISOR', -0x387C, 16,
           'A5-0x387C  read by $263F4.  At the January reconciliation each'
           ' department settles accrued/(12*divisor) into the treasury, so a'
           ' positive entry is revenue and a negative one a cost.')
emit_words('ZONE_ATTRACTS', -0x38BC, 16,
           'A5-0x38BC  read by $24848.  Bit z is set when a trip starting in this'
           ' zone is satisfied by arriving at zone z -- residential seeks commerce'
           ' and industry, commerce seeks residents and industry, and so on.  This'
           ' is the whole of the trip model.')
emit_longs('NAT_ERA_MIX', -0x13D6, 55,
           'A5-0x13D6  five technology eras by eleven industries, read at'
           ' $35566.  The pass interpolates between the era the city is in'
           ' and the next one, by how far through its fifty years it is.')
emit_words('NAT_RATE_TABLE', -0x12EA, 12,
           'A5-0x12EA  read by economyPass at $34E3C, indexed by the national'
           ' cycle at A5+0x1EB0.  Gives the growth rate, in percent per year,'
           ' of the second national indicator.')
emit_longs('CITY_STAGE_POP', -0x3ED8, 10,
           'A5-0x3ED8: population a city must reach to be promoted to the '
           'next stage; simTick phase 22 ($220FA) indexes it with stage + 1 '
           'and a zero entry ends the ladder')
emit_words('BLD_CHOICE_BASE', -0x146E, 20,
           'A5-0x146E  read by $3258A.  Five building kinds by four tiers: the'
           ' first building id of each group.')
emit_words('BLD_CHOICE_COUNT', -0x1446, 20,
           'A5-0x1446  how many variants each group has, so $3258A picks one at'
           ' random within it.')
emit_words('ROT_CORNER_4', -0x7DCC, 16,
           'A5-0x7DCC  four rotations by four sub-tiles: which XZON corner bit'
           ' each tile of a 2x2 building carries. $328EC')
emit_bytes('WALK_TURN_MASK', -0x38AE, 4,
           'A5-0x38AE  the directions still open after a step, read at $251BC.'
           '  Each entry clears the bit for the way the trip just came, so a'
           ' journey never immediately doubles back on itself.')
emit_words('WALK_DY', -0x392C, 4,
           'A5-0x392C  row step per direction 0..3, used by the road walk at $24784.')
emit_words('WALK_DX', -0x3924, 4,
           'A5-0x3924  column step per direction, $24794.')
emit_words('NEIGHBOUR_ORDER', -0x391C, 48,
           'A5-0x391C  24 {dx, dy} pairs: the L1 diamond of radius 3, in the order'
           ' $245E8 and $24530 search it.  The order matters -- $24602 takes the'
           ' first transport tile it finds and reads its type from it.')
# the two tables that live in code rather than data, recovered by running
# the routines that encode them
import gen_coverage, gen_ordinance, gen_walk
w('')
gen_coverage.emit(w)
gen_ordinance.emit(w)
gen_walk.emit(w)

path = os.path.join(os.path.dirname(__file__), "..", "src", "sim", "generated", "tables.c")
open(path, "w").write("\n".join(x for x in out if x is not None) + "\n")

# the generated file is held to the same style as the hand-written ones,
# so `ctest` does not fail the moment the tables are regenerated
import shutil, subprocess
cf = shutil.which("clang-format") or "/opt/homebrew/bin/clang-format"
if os.path.exists(cf):
    subprocess.run([cf, "-i", path], check=False)
print("wrote", os.path.normpath(path), len(out), "lines")
