#  version.cmake -- the version header, written at build time.
#
#  Run in script mode by the arc_version target on every build, with
#  SRC (the source tree), OUT (the header to write) and VERSION (from
#  project()).  It asks git for the commit, whether the tree is clean
#  and the commit's date, and writes the header ONLY when the content
#  changes, so a build that has not moved recompiles nothing.
#
#  Configure time would have been simpler and wrong: the hash would be
#  whatever HEAD was when cmake last ran, which after a few commits is
#  a version string that lies.
find_package(Git QUIET)
set(hash "unknown")
set(dirty 0)
set(date "")
if(GIT_EXECUTABLE)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SRC}" rev-parse --short=7 HEAD
                    OUTPUT_VARIABLE hash OUTPUT_STRIP_TRAILING_WHITESPACE
                    ERROR_QUIET RESULT_VARIABLE rc)
    if(NOT rc EQUAL 0 OR hash STREQUAL "")
        set(hash "unknown")
    else()
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SRC}" status --porcelain --untracked-files=no
                        OUTPUT_VARIABLE st ERROR_QUIET)
        if(NOT st STREQUAL "")
            set(dirty 1)
        endif()
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SRC}" log -1 --format=%cs
                        OUTPUT_VARIABLE date OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    endif()
endif()
if(dirty)
    set(full "${VERSION}+g${hash}.dirty")
else()
    set(full "${VERSION}+g${hash}")
endif()
set(content "/*  arc_version.h -- generated by cmake/version.cmake; do not edit.
 *
 *  ARC_VERSION       semver, from project() in CMakeLists.txt
 *  ARC_GIT           the commit, short
 *  ARC_GIT_DIRTY     1 when the tree had uncommitted changes
 *  ARC_GIT_DATE      the commit's date, YYYY-MM-DD
 *  ARC_VERSION_FULL  semver+g<hash>[.dirty]
 */
#ifndef ARC_VERSION_H
#define ARC_VERSION_H
#define ARC_VERSION \"${VERSION}\"
#define ARC_GIT \"${hash}\"
#define ARC_GIT_DIRTY ${dirty}
#define ARC_GIT_DATE \"${date}\"
#define ARC_VERSION_FULL \"${full}\"
#endif
")
set(old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL content)
    get_filename_component(dir "${OUT}" DIRECTORY)
    file(MAKE_DIRECTORY "${dir}")
    file(WRITE "${OUT}" "${content}")
endif()
